### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by siascone** [lemikee/bytes#3]
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
  - [x] primary key
  - [x] not null
  - [x] unique
  - [x] indexed
  - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
  - [x] schema is written in a table format
  - [x] the table’s name are lowercased, snake_cased and `back_ticked`
  - [x] the table header column names are bolded
  - [x] columns names are lowercased and snaked_cased and `back_ticked`

**Comment by siascone** [comment]
I noticed that you have city and zip code info stored in your database but not state info. Do you plan to have you map extend beyond one stare or are you planning on focusing on just one area?

- missing bullet info from cuisine and business_cuisine tables

**Comment by lemikee** [comment]
I've added state info to the businesses table. I think I'll restrict the map to California for now and add on other states during the post-MERN sprint.
